version: "3.8"

services:

  authorization-server:
    image: xoo0608/authorization-server
    environment:
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    ports:
      - "9000:9000"
    networks:
      - spring-msa-network

  api-gateway:
    image: xoo0608/api-gateway
    ports:
      - "8765:8765"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
      - SPRINGDOC_SWAGGER_UI_URLS_0_NAME=securities-service
      - SPRINGDOC_SWAGGER_UI_URLS_0_URL=http://localhost:8765/api/securities-service/v3/api-docs
      - SPRINGDOC_SWAGGER_UI_URLS_1_NAME=portfolio-backtest-service
      - SPRINGDOC_SWAGGER_UI_URLS_1_URL=http://localhost:8765/api/portfolio-backtest-service/v3/api-docs
      - SPRINGDOC_SWAGGER_UI_URLS_2_NAME=portfolio-composition-service
      - SPRINGDOC_SWAGGER_UI_URLS_2_URL=http://localhost:8765/api/portfolio-composition-service/v3/api-docs
      - SPRINGDOC_SWAGGER_UI_URLS_3_NAME=portfolio-service
      - SPRINGDOC_SWAGGER_UI_URLS_3_URL=http://localhost:8765/api/portfolio-service/v3/api-docs
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - naming-server
    networks:
      - spring-msa-network

  naming-server:
    image: xoo0608/naming-server
    ports:
      - "8761:8761"
    networks:
      - spring-msa-network

  portfolio-backtest:
    image: xoo0608/portfolio-backtest-service
    ports:
      - "8050:8050"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - naming-server
    networks:
      - spring-msa-network

  portfolio-composition:
    image: xoo0608/portfolio-composition-service
    ports:
      - "8040:8040"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - naming-server
    networks:
      - spring-msa-network

  portfolio:
    image: xoo0608/portfolio-service
    ports:
      - "8010:8010"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - naming-server
    networks:
      - spring-msa-network

  securities:
    image: xoo0608/securities-service
    ports:
      - "8000:8000"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://naming-server:8761/eureka
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin-server:9411/api/v2/spans
    depends_on:
      - naming-server
    networks:
      - spring-msa-network

  zipkin-server:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - spring-msa-network
    restart: always

networks:
  spring-msa-network:
    driver: bridge